sudo: required
services:
    - docker

before_install:
    - docker build -t alvin4787/docker-react -f Dockerfile.dev .

script:
    - docker run alvin4787/docker-react npm run test -- --coverage