sudo: required
services:
    - docker

before_install:
    - docker build -t alvin4787/docker-react -f Dockerfile.dev .

script:
    - docker run alvin4787/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ca-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ca-central-1-152348224682"
    bucket_path: "docker-react"
    on:
        branch: master
    acess_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY